apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            name: cronjob
        spec:
          containers:
          - name: stretch
          image: python
          args:
          - python
          - -c
          - from datetime import datetime; print('[{}] Stretch'.format(datetime.now()))
          restartPolicy: OnFailure